//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OG.VUE.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona1
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string APaterno { get; set; }
        public string AMaterno { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<decimal> Estatura { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<System.DateTime> FechaN { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
